= Library System Documentation

== Overview

Welcome to the documentation for Library System, digital platform that allows readers to rent books seamlessly. Documentation use the Structurizer C4 model and visualized through the link:https://github.com/avisi-cloud/structurizr-site-generatr[Structurizr Site Generatr] repository. This documentation provides comprehensive insights into the Library system architecture, including components, containers, processes, and projects details.

== Structurizr Site Generatr

A static site generator for C4 architecture models created with link:https://github.com/structurizr/dsl[Structurizr DSL].

=== Features

* Generate a static HTML site, based on a Structurizr DSL workspace.
* Generates diagrams in SVG, PNG and PlantUML format, which can be viewed and downloaded from the generated site.
* Easy browsing through the site by clicking on software system and container elements in the diagrams.
* Start a development server which generates a site, serves it and updates the site automatically whenever a file that's part of the Structurizr workspace changes.
* Include documentation (in Markdown format) in the generated site. Both workspace level documentation and software system level documentation are included in the site.
* Include ADR's in the generated site. Again, both workspace level ADR's and software system level ADR's are included in the site.
* Include static assets in the generated site, which can be used in ADR's and documentation.
* Generate a site from a Structurizr DSL model in a Git repository. Supports multiple branches, which makes it possible to for example maintain an actual state in `master` and one or more future states in feature branches. The generated site includes diagrams for all valid configured or detected branches.
* Include a version number in the generated site.

=== Installation using Homebrew

As this approach relies on link:https://brew.sh/[Homebrew], ensure this is already installed. For Windows and other operating systems not supported by Homebrew, please use the link:#docker[Docker approach] instead.

To install Structurizr Site Generatr execute the following commands in your terminal:

[source,shell]
----
brew tap avisi-cloud/tools
brew install structurizr-site-generatr

structurizr-site-generatr --help
----

Periodically, you would have to update your local installation to take advantage of any new link:https://github.com/avisi-cloud/structurizr-site-generatr/releases[Structurizr Site Generatr releases].

=== Manual installation

If using Homebrew is not an option for you, it's also possible to install Structurizr Site Generatr manually. This can be done as follows:

- Consult the link:https://github.com/avisi-cloud/structurizr-site-generatr/releases[Structurizr Site Generatr releases] and choose the version you wish to use
- Download the `.tar.gz` or `.zip` distribution
- Extract the archive using your favourite tool
- For ease of use, it's recommended to add Structurizr Site Generatr's `bin` directory to your `PATH`

=== Help

To learn about available commands, or parameters for individual commands, call Structurizr Site Generatr with the `--help` argument.

[source,shell]
----
installed> structurizr-site-generatr --help

Usage: structurizr-site-generatr options_list
Subcommands:
    serve - Start a development server
    generate-site - Generate a site for the selected workspace.
    version - Print version information

Options:
    --help, -h -> Usage info
----

=== Version

To query the version of Structurizr Site Generatr installed / used.

[source,shell]
----
installed> structurizr-site-generatr version

Structurizr Site Generatr v1.1.3
----

=== Generate a local documentation server

==== From a link:https://github.com/structurizr/dsl[C4 Workspace]

This is the primary use case of Structurizr Site Generatr -- to generate a website from a link:https://github.com/structurizr/dsl[C4 Workspace].

[source,shell]
----
installed> structurizr-site-generatr generate-site -w workspace.dsl
----

Here, the `--workspace-file` or `-w` parameter specifies the input link:https://github.com/structurizr/dsl[C4 Workspace DSL file] to the `generate-site` command. Additional parameters that affect website generation can be reviewed using the `--help` operator.

By default, the generated website will be placed in `./build`, which is overwritten if it already exists.

== Customizing the generated website

The site generator use the link:https://github.com/structurizr/export/tree/main/src/main/java/com/structurizr/export/plantuml#c4plantumlexporter[C4PlantUmlExporter] to generate the diagrams. All properties available for the C4PlantUMLExporter, e.g. `c4plantuml.tags`, can be applied and affect the diagrams in the generate site. See also link:https://github.com/structurizr/export/tree/main#diagram-notation[Diagram notation] for an overview of supported features and limitations for this exporter.

The look and feel of the generated site can be customized with several additional view properties in the C4 architecture model:

|===
| Property name                           | Description                                                                                                                                                                                                                                                                                                                                       | Default   | Example

| `generatr.style.colors.primary`         | Primary site color, used for header bar background and active menu background.                                                                                                                                                                                                                                                                    | `#333333` | `#485fc7`

| `generatr.style.colors.secondary`       | Secondary site color, used for font color in header bar and for active menu.                                                                                                                                                                                                                                                                      | `#cccccc` | `#ffffff`

| `generatr.style.faviconPath`            | Site logo location relative to the configured `assets` folder. When configured, the logo image will be placed on the left side in the header bar. This requires the `--assets-dir` switch when generating the site and the corresponding file to be available in the `assets` folder.                                                               |           | `site/favicon.ico`

| `generatr.style.logoPath`               | Site favicon location relative to the configured `assets` folder. When configured, the favicon will be set for all generated pages. This requires the `--assets-dir` switch when generating the site and the corresponding file to be available in the `assets` folder.                                                                        |           | `site/logo.png`

| `generatr.style.customStylesheet`       | URL to hosted custom stylesheet or path to a custom stylesheet file (location relative to the configured `assets` folder). When configured, this CSS file will be loaded for all pages. When using a path to a file, the `--assets-dir` switch must be used when generating the site and the corresponding file is available in the `assets` folder. |           | `site/custom.css` or 'https://uri.example/custom.css

| `generatr.search.language`              | Indexing/stemming language for the search index. See link:https://github.com/olivernn/lunr-languages[Lunr language support]                                                                                                                                                                                                                        | `en`      | `nl`

| `generatr.markdown.flexmark.extensions` | Additional extensions to the markdown generator to add new markdown capabilities. link:https://avisi-cloud.github.io/structurizr-site-generatr/main/extended-markdown-features/[More Details]                                                                                                                                                      | Tables    | `Tables,Admonition`

| `generatr.svglink.target`               | Specifies the link target for element links in the exported SVG.                                                                                                                                                                                                                                                                                   | `_top`    | `_self`

| `generatr.site.nestGroups`              | Will show software systems in the left-side navigator in collapsible groups.                                                                                                                                                                                                                                                                      | `false`   | `true`
|===

See the included example for usage of some of those properties in the link:https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/docs/example/workspace.dsl#L159[C4 architecture model example].
