@startuml
set separator none
title System Landscape

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<Accounts>> {
  BackgroundColor #009688
  FontColor #ffffff
  BorderColor #00695f
  shadowing false
}
skinparam person<<Administrator>> {
  BackgroundColor #00796b
  FontColor #ffffff
  BorderColor #00544a
  shadowing false
}
skinparam rectangle<<Cart>> {
  BackgroundColor #009688
  FontColor #ffffff
  BorderColor #00695f
  shadowing false
}
skinparam rectangle<<Finance>> {
  BackgroundColor #009688
  FontColor #ffffff
  BorderColor #00695f
  shadowing false
}
skinparam rectangle<<MailProvider>> {
  BackgroundColor #4db6ac
  FontColor #ffffff
  BorderColor #357f78
  shadowing false
}
skinparam rectangle<<Products>> {
  BackgroundColor #009688
  FontColor #ffffff
  BorderColor #00695f
  shadowing false
}
skinparam person<<Reader>> {
  BackgroundColor #00796b
  FontColor #ffffff
  BorderColor #00544a
  shadowing false
}
skinparam rectangle<<Recommendations>> {
  BackgroundColor #009688
  FontColor #ffffff
  BorderColor #00695f
  shadowing false
}
skinparam rectangle<<Shelf>> {
  BackgroundColor #009688
  FontColor #ffffff
  BorderColor #00695f
  shadowing false
}

person "==Reader\n<size:10>[Person]</size>\n\nA user of the E-Library System who interacts with available resources." <<Reader>> as Reader
rectangle "==Products\n<size:10>[Software System]</size>\n\nMaintains and displays items available in the library." <<Products>> as Products
rectangle "==Cart\n<size:10>[Software System]</size>\n\nHandles the item rental process." <<Cart>> as Cart
rectangle "==Recommendations\n<size:10>[Software System]</size>\n\nProvides recommended items for users." <<Recommendations>> as Recommendations
person "==Administrator\n<size:10>[Person]</size>\n\nAn admin responsible for adding items to the library, managing user accounts, and handling financial transactions." <<Administrator>> as Administrator
rectangle "==Finance\n<size:10>[Software System]</size>\n\nManages financial transactions and payment processing." <<Finance>> as Finance
rectangle "==Mail Provider\n<size:10>[Software System]</size>\n\nExternal system for sending emails." <<MailProvider>> as MailProvider
rectangle "==Accounts\n<size:10>[Software System]</size>\n\nEnables users to create, view, and update accounts." <<Accounts>> as Accounts
rectangle "==Shelf\n<size:10>[Software System]</size>\n\nStores and displays items borrowed by users." <<Shelf>> as Shelf

Reader .[#004d40,thickness=2].> Accounts : "<color:#004d40>Manages their account."
Reader .[#004d40,thickness=2].> Shelf : "<color:#004d40>Manages borrowed items."
Reader .[#004d40,thickness=2].> Products : "<color:#004d40>Views available items."
Reader .[#004d40,thickness=2].> Cart : "<color:#004d40>Handles rental process."
Reader .[#004d40,thickness=2].> Recommendations : "<color:#004d40>Views recommended items."
Reader .[#004d40,thickness=2].> Finance : "<color:#004d40>Manages payments."
Cart .[#004d40,thickness=2].> Finance : "<color:#004d40>Processes payments."
Administrator .[#004d40,thickness=2].> Accounts : "<color:#004d40>Oversees user accounts."
Administrator .[#004d40,thickness=2].> Products : "<color:#004d40>Manages library items."
Administrator .[#004d40,thickness=2].> Finance : "<color:#004d40>Oversees financial transactions."
MailProvider .[#004d40,thickness=2].> Reader : "<color:#004d40>Sends invoices."
Accounts .[#004d40,thickness=2].> Recommendations : "<color:#004d40>Updates recommendations.\n<color:#004d40><size:8>[Kafka]</size>"
Cart .[#004d40,thickness=2].> Recommendations : "<color:#004d40>Updates recommendations.\n<color:#004d40><size:8>[Kafka]</size>"
Cart .[#004d40,thickness=2].> Shelf : "<color:#004d40>Notifies borrowed items.\n<color:#004d40><size:8>[Kafka]</size>"
Cart .[#004d40,thickness=2].> Products : "<color:#004d40>Checks item availability.\n<color:#004d40><size:8>[HTTPS]</size>"
Finance .[#004d40,thickness=2].> MailProvider : "<color:#004d40>Sends invoices to readers.\n<color:#004d40><size:8>[SMTP]</size>"
@enduml