@startuml
title "Adding book to library"
actor "Library Administrator" as admin
participant "Products Webpage" as productsWebpage
participant "Products" as products

admin -> productsWebpage : add book
productsWebpage -> products : add book
products -> productsWebpage : added
productsWebpage -> admin : added
@enduml