@startuml
title "Adding product to cart"

actor "Reader" as reader
participant "Products Webpage" as productsWebpage
participant "Cart" as cart
participant "Recommendations" as recommendations

== Adding product to cart ==
reader -> productsWebpage : add book to cart
productsWebpage -> cart : add book to cart
cart -> recommendations : add selected book to recommendations
recommendations -> cart : added
cart -> productsWebpage : added
productsWebpage -> reader : added

@enduml