@startuml
title "Finding book"

actor "Reader" as reader
participant "Products Webpage" as productsWebpage
participant "Products" as products
participant "Recommendations" as recommendations

reader -> productsWebpage : present library content
productsWebpage -> products : get available books
products -> productsWebpage : book list
productsWebpage -> recommendations : get reader recommendations
recommendations -> productsWebpage : reader recommendations
productsWebpage -> reader : library content

@enduml