@startuml
title "User Registration"
actor "Reader" as reader
participant "Accounts Webpage" as accountWebpage
participant "Accounts" as accounts
participant "Recommendations" as recommendations

reader -> accountWebpage : create account
accountWebpage -> accounts : create account
accounts -> recommendations : store reader recommendations
recommendations -> accounts : stored
accounts -> accountWebpage : created
accountWebpage -> reader : created
@enduml