@startuml
set separator none
title Cart - Dynamic

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam sequenceParticipant<<Cart.CartDatabase>> {
  BackgroundColor #26a69a
  FontColor #ffffff
  BorderColor #1a746b
  shadowing false
}
skinparam sequenceParticipant<<Cart.CartMicroservice>> {
  BackgroundColor #26a69a
  FontColor #ffffff
  BorderColor #1a746b
  shadowing false
}
skinparam sequenceParticipant<<Cart.CartSPA>> {
  BackgroundColor #26a69a
  FontColor #ffffff
  BorderColor #1a746b
  shadowing false
}
skinparam sequenceParticipant<<Reader>> {
  BackgroundColor #00796b
  FontColor #ffffff
  BorderColor #00544a
  shadowing false
}
skinparam sequenceParticipant<<Recommendations.RecommendationsMicroservice>> {
  BackgroundColor #26a69a
  FontColor #ffffff
  BorderColor #1a746b
  shadowing false
}

actor "Reader\n<size:10>[Person]</size>" as Reader <<Reader>> #00796b
participant "Cart SPA\n<size:10>[Container: React Component]</size>" as Cart.CartSPA <<Cart.CartSPA>> #26a69a
participant "Cart Microservice\n<size:10>[Container: Java and Spring Boot]</size>" as Cart.CartMicroservice <<Cart.CartMicroservice>> #26a69a
database "Cart Database\n<size:10>[Container: MongoDB]</size>" as Cart.CartDatabase <<Cart.CartDatabase>> #26a69a
participant "Recommendations Microservice\n<size:10>[Container: Java and Spring Boot]</size>" as Recommendations.RecommendationsMicroservice <<Recommendations.RecommendationsMicroservice>> #26a69a
Reader -[#004d40]> Cart.CartSPA : Adds item to cart
Cart.CartSPA -[#004d40]> Cart.CartMicroservice : Processes cart addition
Cart.CartMicroservice -[#004d40]> Cart.CartDatabase : Stores cart item
Cart.CartMicroservice <-[#004d40]- Cart.CartDatabase : Confirms storage
Cart.CartMicroservice -[#004d40]> Recommendations.RecommendationsMicroservice : Updates recommendations based on cart activity
Cart.CartMicroservice <-[#004d40]- Recommendations.RecommendationsMicroservice : Acknowledges update
Cart.CartSPA <-[#004d40]- Cart.CartMicroservice : Confirms cart addition
Reader <-[#004d40]- Cart.CartSPA : Displays cart
@enduml