@startuml
set separator none
title Accounts - Containers

left to right direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam database<<Accounts.AccountsDatabase>> {
  BackgroundColor #8e44ad
  FontColor #ffffff
  BorderColor #632f79
  shadowing false
}
skinparam rectangle<<Accounts.AccountsMicroservice>> {
  BackgroundColor #27ae60
  FontColor #ffffff
  BorderColor #1b7943
  shadowing false
}
skinparam rectangle<<Accounts.AccountsSPA>> {
  BackgroundColor #27ae60
  FontColor #ffffff
  BorderColor #1b7943
  shadowing false
}
skinparam person<<Administrator>> {
  BackgroundColor #28b463
  FontColor #ffffff
  BorderColor #1c7d45
  shadowing false
}
skinparam person<<Reader>> {
  BackgroundColor #28b463
  FontColor #ffffff
  BorderColor #1c7d45
  shadowing false
}
skinparam rectangle<<Recommendations>> {
  BackgroundColor #2980b9
  FontColor #ffffff
  BorderColor #1c5981
  shadowing false
}
skinparam rectangle<<Accounts>> {
  BorderColor #1c5981
  FontColor #1c5981
  shadowing false
}

person "==Reader\n<size:10>[Person]</size>\n\nA user of the E-Library System who interacts with available resources." <<Reader>> as Reader
person "==Administrator\n<size:10>[Person]</size>\n\nAn admin responsible for adding items to the library, managing user accounts, and handling financial transactions." <<Administrator>> as Administrator
rectangle "==Recommendations\n<size:10>[Software System]</size>\n\nProvides recommended items for users." <<Recommendations>> as Recommendations

rectangle "Accounts\n<size:10>[Software System]</size>" <<Accounts>> {
  rectangle "==Accounts SPA\n<size:10>[Container: React Component]</size>\n\nProvides account management functionality through the user interface." <<Accounts.AccountsSPA>> as Accounts.AccountsSPA
  rectangle "==Accounts Microservice\n<size:10>[Container: Java and Spring Boot]</size>\n\nAPI for account management functionality." <<Accounts.AccountsMicroservice>> as Accounts.AccountsMicroservice
  database "==Accounts Database\n<size:10>[Container: MongoDB]</size>\n\nHolds user account data." <<Accounts.AccountsDatabase>> as Accounts.AccountsDatabase
}

Reader .[#2980b9,thickness=2].> Recommendations : "<color:#2980b9>Views recommended items."
Reader .[#2980b9,thickness=2].> Accounts.AccountsSPA : "<color:#2980b9>Accesses account functionality."
Administrator .[#2980b9,thickness=2].> Accounts.AccountsSPA : "<color:#2980b9>Manages accounts."
Accounts.AccountsSPA .[#2980b9,thickness=2].> Accounts.AccountsMicroservice : "<color:#2980b9>Requests account operations.\n<color:#2980b9><size:8>[HTTPS]</size>"
Accounts.AccountsMicroservice .[#2980b9,thickness=2].> Accounts.AccountsDatabase : "<color:#2980b9>Stores and retrieves accounts.\n<color:#2980b9><size:8>[JDBC]</size>"
Accounts.AccountsMicroservice .[#2980b9,thickness=2].> Recommendations : "<color:#2980b9>Updates recommendations.\n<color:#2980b9><size:8>[Kafka]</size>"
@enduml