@startuml
set separator none
title Shelf - Dynamic

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam sequenceParticipant<<Reader>> {
  BackgroundColor #00796b
  FontColor #ffffff
  BorderColor #00544a
  shadowing false
}
skinparam sequenceParticipant<<Shelf.ShelfDatabase>> {
  BackgroundColor #26a69a
  FontColor #ffffff
  BorderColor #1a746b
  shadowing false
}
skinparam sequenceParticipant<<Shelf.ShelfMicroservice>> {
  BackgroundColor #26a69a
  FontColor #ffffff
  BorderColor #1a746b
  shadowing false
}
skinparam sequenceParticipant<<Shelf.ShelfSPA>> {
  BackgroundColor #26a69a
  FontColor #ffffff
  BorderColor #1a746b
  shadowing false
}

actor "Reader\n<size:10>[Person]</size>" as Reader <<Reader>> #00796b
participant "Shelf SPA\n<size:10>[Container: React Component]</size>" as Shelf.ShelfSPA <<Shelf.ShelfSPA>> #26a69a
participant "Shelf Microservice\n<size:10>[Container: Java and Spring Boot]</size>" as Shelf.ShelfMicroservice <<Shelf.ShelfMicroservice>> #26a69a
database "Shelf Database\n<size:10>[Container: MongoDB]</size>" as Shelf.ShelfDatabase <<Shelf.ShelfDatabase>> #26a69a
Reader -[#004d40]> Shelf.ShelfSPA : Requests borrowed items view
Shelf.ShelfSPA -[#004d40]> Shelf.ShelfMicroservice : Fetches borrowed items
Shelf.ShelfMicroservice -[#004d40]> Shelf.ShelfDatabase : Retrieves borrowed items data
Shelf.ShelfMicroservice <-[#004d40]- Shelf.ShelfDatabase : Returns borrowed items data
Shelf.ShelfSPA <-[#004d40]- Shelf.ShelfMicroservice : Returns borrowed items to UI
Reader <-[#004d40]- Shelf.ShelfSPA : Displays borrowed items view
@enduml