@startuml
set separator none
title Accounts - Dynamic

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam sequenceParticipant<<Accounts.AccountsDatabase>> {
  BackgroundColor #8e44ad
  FontColor #ffffff
  BorderColor #632f79
  shadowing false
}
skinparam sequenceParticipant<<Accounts.AccountsMicroservice>> {
  BackgroundColor #27ae60
  FontColor #ffffff
  BorderColor #1b7943
  shadowing false
}
skinparam sequenceParticipant<<Accounts.AccountsSPA>> {
  BackgroundColor #27ae60
  FontColor #ffffff
  BorderColor #1b7943
  shadowing false
}
skinparam sequenceParticipant<<Reader>> {
  BackgroundColor #28b463
  FontColor #ffffff
  BorderColor #1c7d45
  shadowing false
}
skinparam sequenceParticipant<<Recommendations.RecommendationsMicroservice>> {
  BackgroundColor #27ae60
  FontColor #ffffff
  BorderColor #1b7943
  shadowing false
}

actor "Reader\n<size:10>[Person]</size>" as Reader <<Reader>> #28b463
participant "Accounts SPA\n<size:10>[Container: React Component]</size>" as Accounts.AccountsSPA <<Accounts.AccountsSPA>> #27ae60
participant "Accounts Microservice\n<size:10>[Container: Java and Spring Boot]</size>" as Accounts.AccountsMicroservice <<Accounts.AccountsMicroservice>> #27ae60
database "Accounts Database\n<size:10>[Container: MongoDB]</size>" as Accounts.AccountsDatabase <<Accounts.AccountsDatabase>> #8e44ad
participant "Recommendations Microservice\n<size:10>[Container: Java and Spring Boot]</size>" as Recommendations.RecommendationsMicroservice <<Recommendations.RecommendationsMicroservice>> #27ae60
Reader -[#2980b9]> Accounts.AccountsSPA : Initiates account registration
Accounts.AccountsSPA -[#2980b9]> Accounts.AccountsMicroservice : Requests new account creation
Accounts.AccountsMicroservice -[#2980b9]> Accounts.AccountsDatabase : Stores new account data
Accounts.AccountsMicroservice <-[#2980b9]- Accounts.AccountsDatabase : Confirms account creation
Accounts.AccountsMicroservice -[#2980b9]> Recommendations.RecommendationsMicroservice : Updates recommendations for new user
Accounts.AccountsMicroservice <-[#2980b9]- Recommendations.RecommendationsMicroservice : Acknowledges recommendation update
Accounts.AccountsSPA <-[#2980b9]- Accounts.AccountsMicroservice : Sends account details
Reader <-[#2980b9]- Accounts.AccountsSPA : Displays created account details
@enduml