@startuml
title "Adding product to cart"

participant "Cart Webpage" as cartWebpage #99FF99
participant "Cart Rest Api" as cartApi
participant "Cart manager" as cartManager
participant "Cart Repository" as repository
database "DynamoDB" as dynamoDb #99FF99
participant "Recommendations Connector" as recommendationConnector
participant "Recommendations" as recommendations #99FF99

cartWebpage -> cartApi : add item to cart
cartApi -> cartManager : add item to cart
cartManager -> repository : create or update user cart
repository -> dynamoDb : create or update user cart
dynamoDb -> repository : stored
repository -> cartManager : stored
cartManager -> recommendationConnector : add selected book to user recommendations
recommendationConnector -> recommendations : add selected book to user recommendations
recommendations -> recommendationConnector : added
recommendationConnector -> cartManager : added
cartManager -> cartApi : added
cartApi -> cartWebpage : added

@enduml