@startuml
title "Prepare cart payment"

participant "Cart Webpage" as cartWebpage #99FF99
participant "Cart Rest Api" as cartApi
participant "Cart manager" as cartManager
participant "Cart Repository" as repository
database "DynamoDB" as dynamoDb #99FF99
participant "Products connector" as productsConnector
participant "Products" as products #99FF99
participant "Cart Calculator" as cartCalculator
participant "Finances Connector" as financesConnector
participant "Finances" as finances #99FF99

cartWebpage -> cartApi : rent items from the cart
cartApi -> cartManager : rent items from the cart

cartManager -> repository : get cart
repository -> dynamoDb : get cart
dynamoDb -> repository : cart
repository -> cartManager : cart

cartManager -> productsConnector : confirm products availability
productsConnector -> products : confirm products availability
products -> productsConnector : products available
productsConnector -> cartManager : products available

cartManager -> cartCalculator : calculate cart cost
cartCalculator -> cartManager : cart cost

cartManager -> financesConnector : prepare payment
financesConnector -> finances : prepare payment
finances -> financesConnector : payment link
financesConnector -> cartManager : payment link

cartManager -> cartApi :  payment link
cartApi -> cartWebpage :  payment link


@enduml