@startuml
set separator none
title Recommendations - Dynamic

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam sequenceParticipant<<Cart.CartMicroservice>> {
  BackgroundColor #26a69a
  FontColor #ffffff
  BorderColor #1a746b
  shadowing false
}
skinparam sequenceParticipant<<Recommendations.RecommendationsDatabase>> {
  BackgroundColor #26a69a
  FontColor #ffffff
  BorderColor #1a746b
  shadowing false
}
skinparam sequenceParticipant<<Recommendations.RecommendationsMicroservice>> {
  BackgroundColor #26a69a
  FontColor #ffffff
  BorderColor #1a746b
  shadowing false
}

participant "Cart Microservice\n<size:10>[Container: Java and Spring Boot]</size>" as Cart.CartMicroservice <<Cart.CartMicroservice>> #26a69a
participant "Recommendations Microservice\n<size:10>[Container: Java and Spring Boot]</size>" as Recommendations.RecommendationsMicroservice <<Recommendations.RecommendationsMicroservice>> #26a69a
database "Recommendations Database\n<size:10>[Container: MongoDB]</size>" as Recommendations.RecommendationsDatabase <<Recommendations.RecommendationsDatabase>> #26a69a
Cart.CartMicroservice -[#004d40]> Recommendations.RecommendationsMicroservice : Notifies added items to cart
Cart.CartMicroservice <-[#004d40]- Recommendations.RecommendationsMicroservice : Acknowledges notification
Recommendations.RecommendationsMicroservice -[#004d40]> Recommendations.RecommendationsDatabase : Stores updated recommendations
Recommendations.RecommendationsMicroservice <-[#004d40]- Recommendations.RecommendationsDatabase : Confirms storage
@enduml