@startuml
set separator none
title Finance - Containers

left to right direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam person<<Administrator>> {
  BackgroundColor #28b463
  FontColor #ffffff
  BorderColor #1c7d45
  shadowing false
}
skinparam rectangle<<Cart>> {
  BackgroundColor #2980b9
  FontColor #ffffff
  BorderColor #1c5981
  shadowing false
}
skinparam database<<Finance.FinanceDatabase>> {
  BackgroundColor #8e44ad
  FontColor #ffffff
  BorderColor #632f79
  shadowing false
}
skinparam rectangle<<Finance.FinanceMicroservice>> {
  BackgroundColor #27ae60
  FontColor #ffffff
  BorderColor #1b7943
  shadowing false
}
skinparam rectangle<<Finance.FinanceSPA>> {
  BackgroundColor #27ae60
  FontColor #ffffff
  BorderColor #1b7943
  shadowing false
}
skinparam rectangle<<MailProvider>> {
  BackgroundColor #e67e22
  FontColor #ffffff
  BorderColor #a15817
  shadowing false
}
skinparam person<<Reader>> {
  BackgroundColor #28b463
  FontColor #ffffff
  BorderColor #1c7d45
  shadowing false
}
skinparam rectangle<<Finance>> {
  BorderColor #1c5981
  FontColor #1c5981
  shadowing false
}

person "==Reader\n<size:10>[Person]</size>\n\nA user of the E-Library System who interacts with available resources." <<Reader>> as Reader
person "==Administrator\n<size:10>[Person]</size>\n\nAn admin responsible for adding items to the library, managing user accounts, and handling financial transactions." <<Administrator>> as Administrator
rectangle "==Cart\n<size:10>[Software System]</size>\n\nHandles the item rental process." <<Cart>> as Cart
rectangle "==Mail Provider\n<size:10>[Software System]</size>\n\nExternal system for sending emails." <<MailProvider>> as MailProvider

rectangle "Finance\n<size:10>[Software System]</size>" <<Finance>> {
  rectangle "==Finance SPA\n<size:10>[Container: React Component]</size>\n\nInterface for financial management." <<Finance.FinanceSPA>> as Finance.FinanceSPA
  rectangle "==Finance Microservice\n<size:10>[Container: Java and Spring Boot]</size>\n\nAPI for finance operations." <<Finance.FinanceMicroservice>> as Finance.FinanceMicroservice
  database "==Finance Database\n<size:10>[Container: PostgreSQL]</size>\n\nHolds financial transaction data." <<Finance.FinanceDatabase>> as Finance.FinanceDatabase
}

Reader .[#2980b9,thickness=2].> Cart : "<color:#2980b9>Handles rental process."
MailProvider .[#2980b9,thickness=2].> Reader : "<color:#2980b9>Sends invoices."
Reader .[#2980b9,thickness=2].> Finance.FinanceSPA : "<color:#2980b9>Makes payments."
Administrator .[#2980b9,thickness=2].> Finance.FinanceSPA : "<color:#2980b9>Oversees financial transactions."
Cart .[#2980b9,thickness=2].> Finance.FinanceMicroservice : "<color:#2980b9>Generates payment link.\n<color:#2980b9><size:8>[HTTPS]</size>"
Finance.FinanceSPA .[#2980b9,thickness=2].> Finance.FinanceMicroservice : "<color:#2980b9>Requests financial operations.\n<color:#2980b9><size:8>[HTTPS]</size>"
Finance.FinanceMicroservice .[#2980b9,thickness=2].> Finance.FinanceDatabase : "<color:#2980b9>Stores and retrieves transactions.\n<color:#2980b9><size:8>[JDBC]</size>"
Finance.FinanceMicroservice .[#2980b9,thickness=2].> MailProvider : "<color:#2980b9>Sends invoices to readers.\n<color:#2980b9><size:8>[SMTP]</size>"
@enduml