@startuml
set separator none
title Finance - Dynamic

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam sequenceParticipant<<Finance.FinanceMicroservice>> {
  BackgroundColor #27ae60
  FontColor #ffffff
  BorderColor #1b7943
  shadowing false
}
skinparam sequenceParticipant<<MailProvider>> {
  BackgroundColor #e67e22
  FontColor #ffffff
  BorderColor #a15817
  shadowing false
}
skinparam sequenceParticipant<<Reader>> {
  BackgroundColor #28b463
  FontColor #ffffff
  BorderColor #1c7d45
  shadowing false
}

participant "Finance Microservice\n<size:10>[Container: Java and Spring Boot]</size>" as Finance.FinanceMicroservice <<Finance.FinanceMicroservice>> #27ae60
participant "Mail Provider\n<size:10>[Software System]</size>" as MailProvider <<MailProvider>> #e67e22
actor "Reader\n<size:10>[Person]</size>" as Reader <<Reader>> #28b463
Finance.FinanceMicroservice -[#2980b9]> MailProvider : Sends invoice to reader
MailProvider -[#2980b9]> Reader : Receives invoice
MailProvider <-[#2980b9]- Reader : Confirms invoice receipt
Finance.FinanceMicroservice <-[#2980b9]- MailProvider : Confirms email sent
@enduml