@startuml
set separator none
title Recommendations - Dynamic

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam sequenceParticipant<<Accounts.AccountsMicroservice>> {
  BackgroundColor #27ae60
  FontColor #ffffff
  BorderColor #1b7943
  shadowing false
}
skinparam sequenceParticipant<<Recommendations.RecommendationsDatabase>> {
  BackgroundColor #8e44ad
  FontColor #ffffff
  BorderColor #632f79
  shadowing false
}
skinparam sequenceParticipant<<Recommendations.RecommendationsMicroservice>> {
  BackgroundColor #27ae60
  FontColor #ffffff
  BorderColor #1b7943
  shadowing false
}

participant "Accounts Microservice\n<size:10>[Container: Java and Spring Boot]</size>" as Accounts.AccountsMicroservice <<Accounts.AccountsMicroservice>> #27ae60
participant "Recommendations Microservice\n<size:10>[Container: Java and Spring Boot]</size>" as Recommendations.RecommendationsMicroservice <<Recommendations.RecommendationsMicroservice>> #27ae60
database "Recommendations Database\n<size:10>[Container: MongoDB]</size>" as Recommendations.RecommendationsDatabase <<Recommendations.RecommendationsDatabase>> #8e44ad
Accounts.AccountsMicroservice -[#2980b9]> Recommendations.RecommendationsMicroservice : Sends user recommendations data
Accounts.AccountsMicroservice <-[#2980b9]- Recommendations.RecommendationsMicroservice : Acknowledges data receipt
Recommendations.RecommendationsMicroservice -[#2980b9]> Recommendations.RecommendationsDatabase : Stores recommendations
Recommendations.RecommendationsMicroservice <-[#2980b9]- Recommendations.RecommendationsDatabase : Confirms storage
@enduml